### ISSUE TITLE
Error GNOME 40

### ISSUE THREAD

**Issue by mende1** [pop-os/gnome-shell-extension-system76-power#61] opened 2021-06-13 18:05 UTC
I'm using arch with GNOME 40, and I just install the extensions by github, and run the make commands.
Gived me a ERROR, which is:

```
Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 1 matched rules; type="method_call", sender=":1.130" (uid=1000 pid=5603 comm="/usr/bin/gnome-shell ") interface="com.system76.PowerDaemon" member="GetProfile" error name="(unset)" requested_reply="0" destination=":1.2" (uid=0 pid=472 comm="/usr/bin/system76-power daemon ")
```

Any solution?

**Comment by jacobgkau** [comment] 2021-06-14 13:21
Duplicate of https://github.com/pop-os/gnome-shell-extension-system76-power/issues/57.

**Closed by jacobgkau** 2021-06-14 13:21 UTC
