### ISSUE TITLE
The extension "system76-power@system76.com" does not exist

### ISSUE THREAD

**Issue by JeanGs97** [pop-os/gnome-shell-extension-system76-power#86] opened 2023-01-14 00:22 UTC
The extension is already installed, I did it with make and make install, I get this:

FOR "make"
UUID is "system76-power@system76.com"
if ! command -v tsc >/dev/null; then \
	echo 'You must install TypeScript >= 3.8 to transpile: (node-typescript on Debian systems)'; \
	exit 1; \
fi
tsc
for file in target/*.js; do \
	sed -i \
		-e 's#export function#function#g' \
		-e 's#export var#var#g' \
		-e 's#export const#var#g' \
		-e 's#Object.defineProperty(exports, "__esModule", { value: true });#var exports = {};#g' \
		"${file}"; \
	sed -i -E 's/export class (\w+)/var \1 = class \1/g' "${file}"; \
	sed -i -E "s/import \* as (\w+) from '(\w+)'/const \1 = Me.imports.\2/g" "${file}"; \
done
rm -rf _build
rm: no se puede borrar '_build/extension.js': Permiso denegado
rm: no se puede borrar '_build/stylesheet.css': Permiso denegado
rm: no se puede borrar '_build/metadata.json': Permiso denegado
make: *** [Makefile:26: compile] Error 1

FOR "sudo make install"
UUID is "system76-power@system76.com"
rm -rf /home/sebas/.local/share/gnome-shell/extensions/system76-power@system76.com
mkdir -p /home/sebas/.local/share/gnome-shell/extensions/system76-power@system76.com
cp -r _build/* /home/sebas/.local/share/gnome-shell/extensions/system76-power@system76.com/

After this, I don't see the extension to activate it in the app, so I used the terminal, "gnome-extensions enable system76-power@system76.com" and it tells me that: The extension "system76-power@system76.com" does not exist
WHAT DID I DO WRONG? WHAT SHOULD I DO?

**Comment by JeanGs97** [comment] 2023-01-14 00:23
I have system76-power correctly installed and functional, I have already switched to dedicated graphics using the commands, but I would love to be able to use the extension.

**Comment by n3m0-22** [comment] 2023-01-14 00:48
Can I get a bit more info. The output of this command `cat /etc/os-release` would be helpful.

**Comment by JeanGs97** [comment] 2023-01-14 00:51
> 

PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by n3m0-22** [comment] 2023-01-14 00:55
Thanks, it should work on there. Let me see if I can reproduce this, and I'll get back to you.

**Comment by n3m0-22** [comment] 2023-01-16 17:57
I was able to reproduce the issue. If you want to build it locally you will need to install TypeScript with the following:

`sudo apt install npm`
`sudo npm install -r typescript@latest`

I would also install `gnome-shell-extension-prefs` if you have not already. 

Another option is to install following the instructions found [here](https://support.system76.com/articles/graphics-switch-ubuntu/).

**Comment by n3m0-22** [comment] 2023-01-20 22:47
I'm closing this as it seems to be working correctly, but I can always reopen if you are still having a problem.

**Closed by n3m0-22** 2023-01-20 22:47 UTC
