### ISSUE TITLE
When the hybrid is selected, my system stays extremely slow.

### ISSUE THREAD

**Issue by ceconelo** [pop-os/gnome-shell-extension-system76-power#90] opened 2023-09-15 18:27 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N: Unable to locate package NAME

**Issue/Bug Description:**
When the hybrid is selected, my system stays extremely slow.

**Steps to reproduce (if you know):**
1. Menu
2. Fully Charged
3. Hybrid Graphics Selection

**Expected behavior:**
That system works fluently.

**Other Notes:**

**Comment by leviport** [comment] 2023-09-15 18:32
Are you using an external display? Sounds like it could be this bug: https://github.com/pop-os/nvidia-graphics-drivers/issues/61

**Comment by ceconelo** [comment] 2023-09-15 18:39
> Are you using an external display? Sounds like it could be this bug: [pop-os/nvidia-graphics-drivers#61](https://github.com/pop-os/nvidia-graphics-drivers/issues/61)

Yes Im using two external display. One in HDMI and other in usb with dock (displaylink).

**Comment by leviport** [comment] 2023-09-15 18:52
The performance issues could partially be due to the DisplayLink dock then. I've never had great luck with their drivers on Linux.

But other than potential DisplayLink issues, I think it's safe to say that this is likely a duplicate of https://github.com/pop-os/nvidia-graphics-drivers/issues/61, which probably means that switching to NVIDIA mode will bring performance back to expected levels.

**Closed by leviport** 2023-09-15 18:52 UTC

**Comment by ceconelo** [comment] 2023-09-15 19:05
> The performance issues could partially be due to the DisplayLink dock then. I've never had great luck with their drivers on Linux.
> 
> But other than potential DisplayLink issues, I think it's safe to say that this is likely a duplicate of [pop-os/nvidia-graphics-drivers#61](https://github.com/pop-os/nvidia-graphics-drivers/issues/61), which probably means that switching to NVIDIA mode will bring performance back to expected levels.

Yes, I did that, but the problem is that in Nvidia mode, the monitor connected to the USB dock (DisplayLink) stops working. :(
