### ISSUE TITLE
Feature request: Start automatically in the baterry mode selected in the last session

### ISSUE THREAD

**Issue by fealv** [pop-os/gnome-shell-extension-system76-power#50] opened 2020-09-21 13:58 UTC
It would be nice if the extension kept the battery mode selected in the previous session, instead of choosing the mode every time you boot the system.

**Comment by jacobgkau** [comment] 2020-09-21 14:25
This may be a duplicate of https://github.com/pop-os/system76-power/issues/2. The system76-power daemon is probably what would need to remember the mode that was selected, not the GNOME shell extension. A config file (or some other method of storing the information) would be a prerequisite to using what was selected in the last session.

**Comment by fealv** [comment] 2020-09-22 14:37
> This may be a duplicate of [pop-os/system76-power#2](https://github.com/pop-os/system76-power/issues/2). The system76-power daemon is probably what would need to remember the mode that was selected, not the GNOME shell extension. A config file (or some other method of storing the information) would be a prerequisite to using what was selected in the last session.

Thank you, it worked well!

**Closed** 2020-09-22 14:38 UTC
